### ISSUE TITLE
Get app data folder automatically 

### ISSUE THREAD

**Issue by thisisthemurph** [CH-CLARK/WalletSleuth#2]
It should be possible to determine the users appdata folder path automatically, rather than asking them for it.

https://stackoverflow.com/a/1225832/1991735

**Comment by CH-CLARK** [comment]
I had considered implementing this using 'os.getenv', it was not implemented to give the user the opportunity to add the AppData folder for other users or add an AppData location that had been copied out.

I may add it as an option to search over the current user in the future.
